---
language: node_js

node_js:
  - lts/*

install:
  - npm install @vue/cli
  - npm install

script:
  - npm test
  - npm run build

deploy:
  provider: firebase
  project: firebase-test
  token:
    secure: jtj2LHo1h5xmofZGz68HPxbEKGU8X+NDDt9rawdRpnF7IRj4iFw3wWiFFC/NmqUuZph8GHFM/yOSsiOELQMz3kpGP70CaCrFGiKKLkvibO/PjSZSfp02hFzBBdhv5k44Iwite/Iwo+E1O6AXeqWNajCKilPqUke5SEiJIbFLv0J5EAdWBS8TW3CiOnQ+nyEtJIjdoxtq8BqX+T8yQwbsHSX6egjK9lqiZ4qdYeJT8882GnPfQFiCbMGwg75SLtZQK9QVSb6qYVRC0Pm69mP4k+ZWSmSHYmtc3GZhC0PVYihJCOyayrLrOJK6TdW9DFJs83N9+OE0crHBrnw/vxegY1U0SRO4uRY7AqixlTigUc9v5DXQlBAkS8xym4WjOE6JdpF/2jIZgTjmd/h+1NwfyhhEYA8j3uIEB/y3cNNxuisaY4tVmB+pJJbJfG+utgToITGVdMW4+6sERrtC/WKbNmTLCDMsaaCBdl7nteBYSW5hgR9sozDeiklUoSaLt+pzcjfd0DSSNkIBF2thoAjI9GxIUAkkYzMVoJJriRkRNmW4rVvb2FmG+bmCXKRC6HLoiRjbM6ZhKBfsrf8xQRnhZeA0ud8hEUvQmWW8HGlBA/p3HZKKUuyKEZbVve3S5hFpfUKsefQk0DXezAGWSCSHV4NJSnMNTq9WzIER0yGk53Y=
